### ISSUE TITLE
OHLC bars should scale

### ISSUE THREAD

**Issue by Ambrase** [klinecharts/KLineChart#227]
Hi

OHLC bars should scale. Their height and width should be dependent on how much bars it is possible to place in the grid

See as an example:
![image](https://user-images.githubusercontent.com/10509268/164946590-179df597-2550-4950-bb29-773b8ae12559.png)
![image](https://user-images.githubusercontent.com/10509268/165177888-f1129cc7-1cd4-481f-a844-2ec18ea6495a.png)

**Comment by liihuu** [comment]
Style, `candle.type: 'OHLC'`

**Comment by Ambrase** [comment]
It isn't thick. As I see it is 1px pen only without possibility to redefine. Or am I wrong?

**Comment by Ambrase** [comment]
![image](https://user-images.githubusercontent.com/10509268/164947708-feb705db-965a-4385-b1c2-1acf409614a3.png)

**Comment by Ambrase** [comment]
The problem is due to hardcoded 0.5 and 1
in these lines 

https://github.com/liihuu/KLineChart/blob/master/src/view/TechnicalIndicatorView.js#L320
https://github.com/liihuu/KLineChart/blob/master/src/view/TechnicalIndicatorView.js#L321
https://github.com/liihuu/KLineChart/blob/master/src/view/TechnicalIndicatorView.js#L322
