### ISSUE TITLE
[Bug] Canvas shapes not aligning

### ISSUE THREAD

**Issue by olablt** [klinecharts/KLineChart#258]
### Version

8.6.0

### Steps to Reproduce

To demonstrate I modified the test file https://github.com/liihuu/KLineChart/blob/master/tests/technical-indicator-template2.html

Changed the bar color to be more clear and height to full:

```
const realBarHeight = barHeight
ctx.globalCompositeOperation = 'source-over'
ctx.fillStyle = 'rgba(0, 155, 69, 0.8)'
```

### Current Behavior

You can see that sometimes the bars align perfectly but most of the time they do not:

![image](https://user-images.githubusercontent.com/674574/176223315-f9c5a9c1-316e-4eae-983f-adc4a1ac16cc.png)

### Expected Behavior

All bars should have no spaces and should not overlap each other

I am coding a Volume Profile indicator and my bars do not have even spaces like in this Tradingview vs Klinecharts bars example:

![image](https://user-images.githubusercontent.com/674574/176243165-73661fd5-c6f9-41b2-b10d-a4ea0c75184e.png)

### Environment

```markdown
- OS: Linux
- Browser: Firefox, Chrome
- Framework:
```

**Comment by olablt** [comment]
Maybe it is related to Pixel perfect rendering?

- https://www.tradingview.com/blog/en/announcing-lightweight-charts-2-0-17910/
- https://github.com/tradingview/lightweight-charts/issues/274
- https://github.com/tradingview/fancy-canvas

**Comment by liihuu** [comment]
Yes, I will optimize the later version. Thank you.

**Comment by liihuu** [comment]
Yes, I will optimize the later version. Thank you.

**Comment by oneart-dev** [comment]
@liihuu any updates? on PC it looks really blurry, but on my mac quite good. Would like to sponsor this fix if you up to it
