### ISSUE TITLE
[Feature] 分时图逻辑补全

### ISSUE THREAD

**Issue by huobingli** [klinecharts/KLineChart#341]
### 需求描述

API中对分时的描述内容较少，请问是否有计划完善分时功能。
1、支持双坐标轴。举例：分时左边Y轴显示数值坐标，右边Y轴显示百分比坐标。
2、支持自定义0轴。举例：以昨收作为分时0轴，且上下居中显示，上下两边的最大值采用两侧与0轴差值绝对值的最大值

### 具体实现

详见需求描述

**Comment by arrebole** [comment]
不同级别的切换怎么实现比较好
