### ISSUE TITLE
[Feature] 是否支持Y轴设置最大最小值和间隔（interval）

### ISSUE THREAD

**Issue by Bellyang** [klinecharts/KLineChart#377]
### Feature Description

当数据跨度比较大时，支持设置最大和最小值，并设置间隔进行展示
否则当左右拖动时Y轴Tick text会上下跳动改变

### To Do

支持在初始化时参入设置进行更改

**Comment by YourShawn** [comment]
我看了参数都是关于X/Y轴的样式，没有设置最大值或者最小值，您用的哪个参数呀？

**Comment by liihuu** [comment]
v10 开始支持
