### ISSUE TITLE
[Feature] 希望增加一个能配置固定x轴坐标数量的配置

### ISSUE THREAD

**Issue by fzlinjianhui** [klinecharts/KLineChart#420]
### 需求描述

比如，x轴坐标显示 3个点：9:30，11:30，15:00，如果当前数据到11:30的话，那么从11:30到15:00区域就不画线，但是要留位置出来，类似下图
![image](https://user-images.githubusercontent.com/13452682/234801582-c2040677-fa2a-4ead-9490-6bc72622110c.png)

### 具体实现

谢谢大佬

**Comment by fzlinjianhui** [comment]
然后整个图表可以配置成固定显示，从x轴的最左边开始画起，现在好像都是从中间开始。

**Comment by sidgwick** [comment]
> 然后整个图表可以配置成固定显示，从x轴的最左边开始画起，现在好像都是从中间开始。

请问这个问题您解决了吗? 我也有类似的需求, 研究了一下这个库的 API, 还是不知道应该怎么做
