### ISSUE TITLE
PC端v9版本的蜡烛图比v8模糊

### ISSUE THREAD

**Issue by xizyj** [klinecharts/KLineChart#426]
### 版本

9.2.1

### 复现步骤

![image](https://user-images.githubusercontent.com/31697483/236820939-8f554395-5745-4d2c-88ad-b9a754b3a1f3.png)
![image](https://user-images.githubusercontent.com/31697483/236821019-87be2bb3-e9e6-4710-9dbc-fe014c1aa1fe.png)
在PC版本上，截了官网两张示例图，上面一张是v8，下面一张是v9，v9版本明显比v8要模糊

### 当前效果

可见复现步骤

### 预期效果

希望蜡烛图能更加清晰

### 环境

```markdown
- 系统:macOS
- 浏览器:MicroSoft Edge
```

**Comment by liihuu** [comment]
设备像素比是多少

**Comment by xizyj** [comment]
1920 × 1080

**Comment by sirokuma2023** [comment]
你不是一个人这么认为，总感觉比8.0模糊一点

**Comment by liihuu** [comment]
v9.3.0稍微修改了一下，可以升级再看看

**Comment by sirokuma2023** [comment]
> v9.3.0稍微修改了一下，可以升级再看看

我更新了，还是没有改变呀。这是我拿放大镜看的：
![image](https://github.com/liihuu/KLineChart/assets/130817571/a2f9c065-2f29-4616-bf83-15a288c4ba3f)
8.0版本 实体部分都没有模糊
![image](https://github.com/liihuu/KLineChart/assets/130817571/15476ce6-6b72-40b2-8556-64d95c92c0ff)

**Comment by xizyj** [comment]
mac笔记本上是很清楚的，不会糊，外接1920*1080显示器，显示器上就模糊了

**Comment by rockliuxn** [comment]
这个问题在v9.5.0还是存在，第一次打开模糊，当刷新页面之后就显示正常(清晰)

- 第一次打开
    <img width="729" alt="image" src="https://github.com/liihuu/KLineChart/assets/7591665/f785329d-47d2-4c7e-af75-502610c4eecc">

- 刷新之后
    <img width="727" alt="image" src="https://github.com/liihuu/KLineChart/assets/7591665/3818142d-7d28-42a3-9d65-399974bd30ec">


@liihuu  大佬，这个有办法解决吗？

**Comment by liihuu** [comment]
> 这个问题在v9.5.0还是存在，第一次打开模糊，当刷新页面之后就显示正常(清晰)
> 
> * 第一次打开
>   <img alt="image" width="729" src="https://user-images.githubusercontent.com/7591665/250021909-f785329d-47d2-4c7e-af75-502610c4eecc.png">
> * 刷新之后
>   <img alt="image" width="727" src="https://user-images.githubusercontent.com/7591665/250022130-3818142d-7d28-42a3-9d65-399974bd30ec.png">
> 
> @liihuu 大佬，这个有办法解决吗？

需要一个能够复现的最小可执行代码

**Comment by Aruelius** [comment]
在 Windows 上，普通的显示器，缩放比 100%，打开预览页：https://preview.klinecharts.com/

就是模糊的，V8 确实是清晰的

**Comment by 86maid** [comment]
修复好了吗，很急!

**Comment by dotnet22** [comment]
@liihuu @86maid This solved blurry candles issue - I removed border around candles

![image](https://github.com/liihuu/KLineChart/assets/3767382/ad44d1dc-3f9e-4fce-a1e6-1533098a7e55)
![image](https://github.com/liihuu/KLineChart/assets/3767382/ce70bcc2-f504-494a-9562-63fd98ef227b)

**Comment by liihuu** [comment]
#496
