### ISSUE TITLE
[Bug] consider using devicePixelContentBox to fix blur

### ISSUE THREAD

**Issue by oneart-dev** [klinecharts/KLineChart#452]
### Version

9.5.0

### Steps to Reproduce

1. Open chart on PC

### Current Behavior

For PC users chart bars and text can be blurry. 

### Expected Behavior

It's probably not easy fix to make pixel perfect render, but big chunk of users using Chrome or Chromium based browsers and for them we can use this - https://web.dev/device-pixel-content-box/
I didn't managed to apply it properly outside library code, but maybe you have morel luck

### Environment

```markdown
- OS: Windows
- Browser: Chrome
- Framework: not related
```

### Any additional comments?

Confirmed blur on 27'' display with 2560x1440 resolution on latest chrome

**Comment by liihuu** [comment]
Welcome to PR

**Comment by oneart-dev** [comment]
@liihuu after quite a few hours of debugging i probably found the problem with blur. Scrolling is very smooth, but endup with very long floating point. Using Math.floor on bars helps a lot. I will prepare PR. 

Also have a question, why you are using "rect" to draw a wick with fixed 1 width for candle chart. I think migrating to line can improve performance but need testing. Probably new simple line without logic for smoothing can be even faster

**Comment by liihuu** [comment]
Upgrade 9.7.1

**Comment by oneart-dev** [comment]
@liihuu nope, I assume docs running on latest version. This is how it looks here: https://klinecharts.com/en-US/sample/indicator.html

Pay attention to green candles blur
<img width="429" alt="Screenshot 2023-12-23 at 14 47 20" src="https://github.com/klinecharts/KLineChart/assets/70148117/b3af44fe-6b89-4c93-85a2-cd62787a1800">
