### ISSUE TITLE
[Bug] overlay with point in the future does not saving right

### ISSUE THREAD

**Issue by oneart-dev** [klinecharts/KLineChart#459]
### Version

9.5.9

### Steps to Reproduce

1. Draw segment or any 2 point overlays with second point beyond last candle (future)
2. Check overlay points data

### Current Behavior

If check points data it will looks li that:
```json
{
"points":[{"timestamp":1687420800000,"value":0.09349152777777778},{"value":0.1189336111111111}]}
}
```

It will lead to bugs if saving it and restore later

### Expected Behavior

Chart should calculate timestamp based on interval and point location or do not let user to make point in the future

### Environment

```markdown
- OS: Macos
- Browser: any
- Framework: not related
```

**Comment by oneart-dev** [comment]
https://github.com/liihuu/KLineChart/assets/70148117/bb9f8c49-bdc2-44cf-af43-7414f05d5cba

**Comment by oneart-dev** [comment]
Vest possible fix probably will be draw invisible candles all the way to the right.
Sadly "performEventMoveForDrawing" do not provide kline data as all, so it really hard to implement dirty fix to stop users from drawing beyond last candle

**Comment by liihuu** [comment]
It may not be necessary to change the source code, listen to the onDrawing of overlay, and then determine if it exceeds the boundary, forcing a reassignment of points.

**Comment by Basttyy** [comment]
> It may not be necessary to change the source code, listen to the onDrawing of overlay, and then determine if it exceeds the boundary, forcing a reassignment of points.

I noticed this too

**Comment by oneart-dev** [comment]
But its not a solution for the problem. If library can't handle it it should force it by default.

**Comment by xtrmus** [comment]
https://github.com/liihuu/KLineChart/assets/24972453/8dac81ab-68d2-4e09-b7cf-f8ed27ad4189


Likewise, if the starting and ending points are too far apart, the overlay remains hidden when LoadMore is not performed.
