### ISSUE TITLE
Load future data?

### ISSUE THREAD

**Issue by itzTheMeow** [klinecharts/KLineChart#472]
### Feature Description

Can the charts load data from the future? I want the chart to start in the past instead of real time. I did this by fetching kline data for a specific timestamp and then using that in the chart, which works when i scroll to the left (in the past). But if i scroll to the right (in the future) it doesn't call `loadMore` and try to load more data.

### To Do

N/A

**Comment by itzTheMeow** [comment]
[Screencast from 08-12-2023 01:37:09 AM.webm](https://github.com/liihuu/KLineChart/assets/50887230/c0efda68-ef17-4d7f-b68d-29c65d3212cf)

**Comment by DGabri** [comment]
Hi, could you please share how are you able to not make the chart zoom back at the last candle when you call loadMore() and new data is added? Documentation is very unclear for a lot of functions, awesome library but very unclear docs. 
Thanks

**Comment by itzTheMeow** [comment]
@liihuu

**Comment by liihuu** [comment]
`updateData`

**Comment by itzTheMeow** [comment]
how do i make it fetch when i scroll to the right? there doesn't seem to be an event for it.

**Comment by just-rich** [comment]
Yeah we certainly need this, i just made a feature request post about it.

**Comment by itzTheMeow** [comment]
@liihuu any status on this?

**Comment by liihuu** [comment]
#442
