### ISSUE TITLE
Possibility, to add more Data.

### ISSUE THREAD

**Issue by mosaikme** [klinecharts/KLineChart#500]
### Feature Description

Hey, first Thanks for this Libary, Love it. I think a one or two more ,futures. And its the King in Finance Ploting!
I Wonder if it is possible , to just add new rows, for example have candlestick in the first, a custom line series in the second, another custom bar in the Third , and so on.

So we can feed in multiple series. 
Not just one OHLC, and than do TA´s from it. 
We need the possibility , to input more data(custom Data).
For example TA-Lib ta´s , or Custom Data We wrote or get, somewhere else . etc.

Greetings

### To Do

1. Access to the axes.  Like Subplots in Plotly
2. Possibility to add more custom data.

**Comment by liihuu** [comment]
Custom indicator may be able to achieve these.

**Comment by mosaikme** [comment]
Thanks for the fast reply, sorry lots of work at the moment , do you have an idea how? maybe an Example. I think iam not the only one that wants that. Greetings
