### ISSUE TITLE
官网给的预览功能图看着很模糊[Bug] 

### ISSUE THREAD

**Issue by biology-w** [klinecharts/KLineChart#508]
### Version

9.6.0

### Steps to Reproduce

页面展示图地址：https://preview.klinecharts.com/

### Current Behavior

页面展示图地址：https://preview.klinecharts.com/

### Expected Behavior

对比其他展示图：https://cn.tradingview.com/chart/bUemcFvX/

### Environment

```markdown
- OS: windows10
- Browser:chrome最新版
- Framework: 你们官网案例
```

**Comment by biology-w** [comment]
模糊图：
![image](https://github.com/liihuu/KLineChart/assets/25600705/f792a8fb-bc1c-4047-9dba-77c6c992e6d0)

对比其他图：地址https://cn.tradingview.com/chart/bUemcFvX/
![image](https://github.com/liihuu/KLineChart/assets/25600705/81c8da70-e399-4e0e-8d53-76a9ad137374)

**Comment by liihuu** [comment]
Upgrade 9.7.1
