### ISSUE TITLE
registerIndicator重新calc的时候数据表现不一致[Bug] 

### ISSUE THREAD

**Issue by xiatian12345** [klinecharts/KLineChart#512]
### 版本

9.6.0

### 复现步骤

按照官方的例子调用的registerIndicator
界面只有一个切换前后数据的逻辑
切换的时候有很大概率每次不一致

### 当前效果

同样的数据，registerIndicator的calc切换不一致

### 预期效果

同样的数据，registerIndicator的calc切换保持一致

### 环境

```markdown
- 系统:macos
- 浏览器:chrome
- 框架:svelte
```

### 补充说明

确实很诡异。。

**Comment by liihuu** [comment]
创建指标是createIndicator，calc方法也只有在create之后才会执行，这和register没有关系。
