### ISSUE TITLE
[Feature] 涨跌额

### ISSUE THREAD

**Issue by summer233333** [klinecharts/KLineChart#517]
### Feature Description

目前只有涨跌幅【百分比】，希望能有一个涨跌额可以显示
![image](https://github.com/klinecharts/KLineChart/assets/40909307/5ee26fd9-3a20-45bc-980d-55feb2e7f219)

### To Do

涨跌额直接放到涨跌幅后面或者新加一个字段
![image](https://github.com/klinecharts/KLineChart/assets/40909307/8a0ddfd1-e6e4-460a-8076-77c5f05d0d75)

**Comment by liihuu** [comment]
样式配置`candle.tooltip.custom`

**Comment by summer233333** [comment]
![image](https://github.com/klinecharts/KLineChart/assets/40909307/d5af29f5-2381-4fbc-b01c-18378fa810e0)
![image](https://github.com/klinecharts/KLineChart/assets/40909307/331b3f12-9188-4a83-8a1a-1447fe800c36)
![image](https://github.com/klinecharts/KLineChart/assets/40909307/14c8410f-4b18-4cb6-81c0-ec7f688119cd)

**Comment by WLyKan** [comment]
``> ![image](https://private-user-images.githubusercontent.com/40909307/290471719-d5af29f5-2381-4fbc-b01c-18378fa810e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzM3NjIsIm5iZiI6MTcyODk3MzQ2MiwicGF0aCI6Ii80MDkwOTMwNy8yOTA0NzE3MTktZDVhZjI5ZjUtMjM4MS00ZmJjLWIwMWMtMTgzNzhmYTgxMGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2MjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMmQxYWE2ODE5MTExNmU3MDA4MGFiYzc3ZTQwMjcyZDY0ZTIzNmU5NzNmZjQzYWE1ODU1MTZlZjMwODJiZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.efj30tc6VE6hkAqju4pU8lhoZVeo5vA9S2trwKk7BUg) ![image](https://private-user-images.githubusercontent.com/40909307/290472151-331b3f12-9188-4a83-8a1a-1447fe800c36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzM3NjIsIm5iZiI6MTcyODk3MzQ2MiwicGF0aCI6Ii80MDkwOTMwNy8yOTA0NzIxNTEtMzMxYjNmMTItOTE4OC00YTgzLThhMWEtMTQ0N2ZlODAwYzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2MjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ODRmNGRmODcwZWM1NzJlZWYxMWViYTk5NDkxOGIzZWNmMTRiYzg1YTM4OTg5MjA4NjUxZDRmZTNmOTgxZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cx2mHBjToBGfnfOF9dJYGvJHnnabcrjuR-ADVYBzspk) ![image](https://private-user-images.githubusercontent.com/40909307/290472299-14c8410f-4b18-4cb6-81c0-ec7f688119cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzM3NjIsIm5iZiI6MTcyODk3MzQ2MiwicGF0aCI6Ii80MDkwOTMwNy8yOTA0NzIyOTktMTRjODQxMGYtNGIxOC00Y2I2LTgxYzAtZWM3ZjY4ODExOWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA2MjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiYWY2M2FhYzE4OGRjODQ5NWIyZDQ3NjYxYjFhNTYzMWUxN2QzMzVkZTJlNmE0MWVhNmMyNjVlYjk0ZTI2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.H3IS0-Uq4q8RdpW6242zXIo3m34f1hXsHv1U79KIcGE)

value 需要传入模版字符串，不能是变量
```js
      custom: (data: Record<string, KLineData>, styles) => {
        const current = data.current
        const prevClose = data.prev?.close ?? current.close
        const changeValue = current.close - prevClose

        return  [
//...
          {
            title: { text: 'rate', color: '#86909C' },
            value: {
              text: `${data.current.rate}`,
              color: changeValue === 0 ? styles.priceMark.last.noChangeColor : (changeValue > 0 ? styles.priceMark.last.upColor : styles.priceMark.last.downColor),
            } ,
          },
        ];
      },
```
