### ISSUE TITLE
[Feature] 支持通达信脚本吗

### ISSUE THREAD

**Issue by linketian** [klinecharts/KLineChart#524]
### 需求描述

支持通达信脚本吗

### 具体实现

例如MA均线
`
MA1:MA(CLOSE,M1);
MA2:MA(CLOSE,M2);
MA3:MA(CLOSE,M3);
MA4:MA(CLOSE,M4);
`

**Comment by liihuu** [comment]
不支持，你可以自己写解析器，将通达信脚本解析成自定义指标
