### ISSUE TITLE
[Feature] It is possible to add an indicator on the chart alone, without the candlestick chart?

### ISSUE THREAD

**Issue by Arnau-Gelonch** [klinecharts/KLineChart#529]
### Feature Description

I have been trying to add a chart with the MACD without any candlestick or line chart or anything else, and I have not succeeded, I wanted to ask if anyone has done it or if it is possible to do it.

### To Do

- Display a chart with a single indicator without a price chart.

**Comment by char101** [comment]
What do you want to do in the first place?

To answer your question, I don't think the candlestick chart can be removed but if you just want to hide it you can set the MACD indicator pane height to the height of the chart `div` element minus some value to account for the axis height.

**Comment by char101** [comment]
You are asking a candlestick chart library to hide the candlestick?

MACD is just a line chart, there are lots of other charting libraries (plotly, hvplot, etc.) that can plot line charts.

**Comment by Arnau-Gelonch** [comment]
I think it is a library of trading charts, not candlestick charts, and as such it should be able to show only one indicator I think.

**Comment by char101** [comment]
Klinecharts is what candlestick is called in China, so it is literally in the name.

It is basically a clone of tradingview. Can you hide the candlestick in tradingview? You can hide the plot, but the canvas area is still there. If you want to make a MACD only chart in tradingview, what you can do is drag the MACD until it fill the candlestick area, which is what I have written above.

Like I said, if you only want to plot MACD, there are easier charting libraries out there.

**Comment by liihuu** [comment]
Starting from 9.6.0, the layout attribute is supported during initialization, which can be implemented.
