### ISSUE TITLE
[Feature] k线更新的时候，指标的数据是全部重新从头计算一遍的吗？

### ISSUE THREAD

**Issue by heimo88** [klinecharts/KLineChart#535]
### 需求描述

我看代码好像是 每次update 更新k线数据，调用各个指标的 calc 函数，重新遍历一次所有数据计算的吗？
可能是我看的不对，如果是只更新最新的指标数据，请忽略！
感谢作者的付出！

### 具体实现

这个应该可以第一次计算全部，然后下次更新只计算 新更新部分的数据吧，或者是根据设置的周期更新最新的数据，如果历史数据很多的话，几秒更新一次数据是不是循环太多次了。

**Comment by liihuu** [comment]
#203
