### ISSUE TITLE
[Bug] setLoadDataCallback not triggered

### ISSUE THREAD

**Issue by sazanof** [klinecharts/KLineChart#540]
### Version

9.8.0

### Steps to Reproduce

Hello! I'm using klinechart with vue3. and I ran into the problem of automatically loading a part of the candles when I move around the chart (I pull in the earliest candle). 

```
this.chart = init(this.idStr)
await this.getCandles()
this.chart.applyNewData(this.candles) // candles on chart
this.chart.setLoadDataCallback(data => {
     console.log(data) // when candles on a chart, at boot, CB is fire
})
```

### Current Behavior

setLoadDataCallback loads candles at once

### Expected Behavior

setLoadDataCallback loads candles when I reach the end (first candles) of the chart too

### Environment

```markdown
- OS: Ubuntu 22.04
- Browser: Chrome
- Framework: Vue + Laravel
```

### Any additional comments?

`setLoadDataCallback` is used to replace `loadMore`. It is expected that it will work the same way as `loadMore` . 

But it "shoots" only once after the initial data download and that's it. No matter how you move the chart, the event does not fire. How to use `setLoadDataCallback`  correctly? 

It would be nice if you expand the documentation or explain.

**Comment by liihuu** [comment]
```js
data.callback([......], true)
```
Must tell the chart if there is more.

**Comment by sazanof** [comment]
> Must tell the chart if there is more.

Thank you for quick reply! Yes, I did it.
That is, the entire download takes place as long as there is historical data in automatic mode (from docs: "**auto** **load** data callback") after first chart initialization?
It is possible to load data as needed (after moving the chart to the earliest candle?)

**Comment by sazanof** [comment]
Thanks, I've solved the problem. Now, when I load the data in the correct order, everything works, as soon as I stretch the chart to the early candle, the event is triggered. It probably didn't work, because the data was given in a different order, but I didn't notice it. Thanks!

```
this.chart.setLoadDataCallback(async data => {
                this.fromCandle = data
                console.log(data)
                await this.getCandles()
                data.callback(this.candles, true)
 })
```

**Comment by rimzzlabs** [comment]
Hi, how do you solve when trying to see historical data? I know the parameters from LoadDataCallback has type, data, and callback itself, but type is an enum and I cannot import it from the library, any solution to this?
