### ISSUE TITLE
[Bug] UI bug on price YAxis introduced in 9.8.2

### ISSUE THREAD

**Issue by jose-donato** [klinecharts/KLineChart#544]
### Version

9.8.2

### Steps to Reproduce

1. Go to https://klinecharts.com/en-US/sample/basic.html

<img width="1090" alt="image" src="https://github.com/klinecharts/KLineChart/assets/43375532/1075dfa7-36a8-4281-8e88-50be814bf7c9">

### Current Behavior

The whole axis is blurred

### Expected Behavior

This doesn't happen on the version 9.8.1

### Environment

```markdown
- OS: MacOS 14.4
- Browser: Edge
- Framework: React@18
```

### Any additional comments?

Thank you for all your work and this amazing library

**Comment by liihuu** [comment]
The website example code is special and should not have any issues in actual use. I will fix it.
