### ISSUE TITLE
[Feature] Set different color when adding new indicator by default

### ISSUE THREAD

**Issue by zed-wong** [klinecharts/KLineChart#545]
### Feature Description

When using chart.createIndicator to create more indicators, the color would remain the same with the first indicator. Which make it hard to identify. It would be nice that the color of new indicator can be different color by default.
![Screenshot from 2024-03-28 15-31-14](https://github.com/klinecharts/KLineChart/assets/36271125/300a09c9-a325-4679-8613-15021cb0c72b)

### To Do

todo:
1. Set different color for newly added indicators

**Comment by liihuu** [comment]
```js
createIndicator({
  name: '...',
  styles: {
    bars: [......],
    lines: [......]
  }
})
```

**Comment by zed-wong** [comment]
> ```js
> createIndicator({
>   name: '...',
>   styles: {
>     bars: [......],
>     lines: [......]
>   }
> })
> ```

I understand. But I suppose it's better to be done automatically, since the lib wants the best user experience
