### ISSUE TITLE
[Bug] 游览器窗口切出去在切回来，k线图空白了

### ISSUE THREAD

**Issue by beehive-token** [klinecharts/KLineChart#548]
### 版本

9.8。2

### 复现步骤

<img width="1505" alt="image" src="https://github.com/klinecharts/KLineChart/assets/166284956/ebe33e06-a0c4-4a24-adac-3d1c01823b01">
<img width="1511" alt="image" src="https://github.com/klinecharts/KLineChart/assets/166284956/4c1583e8-d19b-4860-87ab-1e74ebf70a7c">
第一张是正常的情况，当我切换游览器的标签卡，然后在切回来，就空白了

### 当前效果

k线空白

### 预期效果

k线正常显示

### 环境

```markdown
- 系统:macOS Monterey
- 浏览器:Chrome 123.0.6312.107
- 框架: vue2 若依的框架
```

**Comment by liihuu** [comment]
可以监听浏览器tab页是否显示来调用下`resize()`临时解决下问题。
