### ISSUE TITLE
[Bug] thousandsSeparator and decimalFoldThreshold options

### ISSUE THREAD

**Issue by haydar-can** [klinecharts/KLineChart#553]
### 版本

9.8.5

### 复现步骤

![electron_MaTGbDkIX6](https://github.com/klinecharts/KLineChart/assets/144682/2237d13c-9b89-46d6-9f5d-5b9e7138ec13)

When I enter values ​​into the decimalFoldThreshold and thousandsSeparator fields while installing, the numbers appear like this.

Values ​​I use:
thousandsSeparator: '.',
decimalFoldThreshold:2

### 当前效果

-

### 预期效果

-

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by liihuu** [comment]
This is a bug, but I think it's a bad setting.
