### ISSUE TITLE
再布局中使用width100% flex 1 等自适应，但是拖动画面的时候图表不会自动自适应

### ISSUE THREAD

**Issue by gh81997167** [klinecharts/KLineChart#554]
### 需求描述

再布局中使用width100% flex 1 等自适应，但是拖动画面的时候图表不会自动自适应

### 具体实现

再布局中使用width100% flex 1 等自适应，但是拖动画面的时候图表不会自动自适应

**Comment by liihuu** [comment]
监听容器尺寸变化，手动调用`resize()`
