### ISSUE TITLE
[Feature] 单独设置每根蜡烛图的颜色

### ISSUE THREAD

**Issue by ooyeah** [klinecharts/KLineChart#555]
### 需求描述

希望每根K线可以自定义颜色，这样可以实现不同波段显示不同的颜色。

<img width="359" alt="image" src="https://github.com/klinecharts/KLineChart/assets/21375553/0c637a8f-b770-42f5-866b-ba3e495f3f2b">

### 具体实现

增加颜色作为数据项一起传进去设置单个蜡烛图的颜色

// 为图表添加数据
    chart.applyNewData([
      { **color: '#FF0000',** close: 4976.16, high: 4977.99, low: 4970.12, open: 4972.89, timestamp: 1587660000000, volume: 204 },
      { **color: '#AAAAAA',** close: 4977.33, high: 4979.94, low: 4971.34, open: 4973.20, timestamp: 1587660060000, volume: 194 },
    ])

**Comment by liihuu** [comment]
可以用自定义指标覆盖原有的k线柱实现

**Comment by yokiyokiyoki** [comment]
我是建议 可以用函数实现这个style里面样式，传参可以当前柱子，下个柱子，价格这些（参考echarts），然后里面的颜色可以动态算出来。自义定指标有点过于麻烦了..

**Comment by jieny** [comment]
@liihuu 大佬，能给个示例吗？
