### ISSUE TITLE
[Feature] i want to make ichimoku indicator

### ISSUE THREAD

**Issue by mooksama** [klinecharts/KLineChart#560]
### Feature Description

hi 
i'm very useful kchart
i want to make ichimoku indicator
but figures offset is not move front or back

How do I make the clouds in the foreground?
And I think it would be nice if I could fill the clouds with color.

![20240517_010850](https://github.com/klinecharts/KLineChart/assets/40266141/f69a5f46-b6cd-46ff-beda-fc9fd7e4f8cd)  

### To Do

how to make it

**Comment by liihuu** [comment]
Custom indicator can do it.

**Comment by mooksama** [comment]
> Custom indicator can do it.

I know. I can make another indicator but i could't make cloud in front. Could you please give me a little bit of explanation?

**Comment by zuri0** [comment]
@mooksama any luck?
