### ISSUE TITLE
[Feature]   Auto(fits data to screen)  

### ISSUE THREAD

**Issue by QGB** [klinecharts/KLineChart#561]
### Feature Description

tradingview 这个一键缩放到合适比例功能，并且可以锁定

### To Do

KLineChart 中用哪个API

**Comment by QGB** [comment]
![image](https://github.com/klinecharts/KLineChart/assets/8005654/2e51d3b9-b9ce-46a6-a552-24e531de4bce)

**Comment by liihuu** [comment]
暂不支持

**Comment by QGB** [comment]
> 暂不支持

别关，有开发计划吗

**Comment by liihuu** [comment]
不会额外新增api，你可以用现有api组合实现

**Comment by QGB** [comment]
> 不会额外新增api，你可以用现有api组合实现

有代码例子可以参考吗
