### ISSUE TITLE
[Bug] Edit numbers after the decimal point

### ISSUE THREAD

**Issue by IlanKalendarov** [klinecharts/KLineChart#571]
### Version

9.8.10

### Steps to Reproduce

I want to show data for the forex symbol GBPUSD and because KlineChart only shows 2 numbers after the decimal point it looks like this:

![image](https://github.com/klinecharts/KLineChart/assets/43996999/43eb9891-00d6-4bee-9461-8c75fae06dc4)

For example in tradingview it looks like this:
![image](https://github.com/klinecharts/KLineChart/assets/43996999/44316e13-3269-42c2-bfc3-ff2856a0798c)
 
 
 Is there a way to show more numbers after the decimal point?

### Current Behavior

-

### Expected Behavior

-

### Environment

```markdown
- OS:Mac Os
- Browser: Chrome
- Framework: Vue js
```

**Comment by liihuu** [comment]
https://klinecharts.com/en-US/more/faq#the-candle-shows-a-line-no-fluctuation-what-to-do
