### ISSUE TITLE
[Bug] Overlay created using chart.createOverlay() has empty string for id

### ISSUE THREAD

**Issue by char101** [klinecharts/KLineChart#574]
### Version

main

### Steps to Reproduce

In this code

https://github.com/klinecharts/KLineChart/blob/045973502f210bd92c060c0ac0cb136d64777106/src/component/Overlay.ts#L351-L357

`this._overlay.id` is `''`, thus `isString(id)` is true, causing `''` to replace back the correct id.

Thus the correct code should be

```typescript
    if (isString(id) && id !== '') {
      this._overlay.id = id
    }
```

**Comment by liihuu** [comment]
Fixed it.
