### ISSUE TITLE
[Bug] How to change the candle color using indicator?

### ISSUE THREAD

**Issue by ajnaduvil** [klinecharts/KLineChart#578]
### Version

latest

### Steps to Reproduce

How can I change the color of the individual candles based on some condition in an indicator

### Current Behavior

I couldn't see an option change the candle color

### Expected Behavior

an option to change the candle color in an indicator

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by liihuu** [comment]
You can use custom indicators to draw candlesticks over the current.
