### ISSUE TITLE
[Bug] 关于在React Native 中使用的问题，

### ISSUE THREAD

**Issue by wuweiliyou** [klinecharts/KLineChart#582]
### 版本

9.8.10

### 复现步骤

新建一个rn项目，然后按照教程使用，

### 当前效果

![image](https://github.com/user-attachments/assets/35b6af11-33bc-4f13-932c-710356e77162)

完全无法使用，直接报错
1.rn不支持 div 元素
2.rn没有document元素会报错，

### 预期效果

希望更新文档，谢谢

### 环境

```markdown
- 系统:android
- 浏览器:
- 框架:rn
```

**Comment by tomheo11233aA** [comment]
Looks like kline doesn't support in react-native platform. Currently I am using webview to display into the application.
