### ISSUE TITLE
[Feature] 怎样在图表中画一条直线，像priceMark一样，但是可以灵活设置值

### ISSUE THREAD

**Issue by taojunnan** [klinecharts/KLineChart#586]
### 需求描述

priceMark是自动最高最低最新值，有没有什么办法可以画这么一条线，但是值可以自己设定？

### 具体实现

如上描述

**Comment by LeeZChuan** [comment]
官方文档提到了这个在画布上绘制基础图形的方法，具体参考使用这个方法即可
`
// 获取基础图形实例
// name为基础图形名字，如，'arc', 'circle'等。
const Figure = klinecharts.getFigureClass(name);
// 实例化并绘制
// attrs 属性
// styles 样式
// ctx 画布上下文
new Figure({ attrs, styles }).draw(ctx);
`

**Comment by taojunnan** [comment]
> 官方文档提到了这个在画布上绘制基础图形的方法，具体参考使用这个方法即可
> 
> ```js
> // 获取基础图形实例
> // name为基础图形名字，如，'arc', 'circle'等。
> const Figure = klinecharts.getFigureClass(name);
> // 实例化并绘制
> // attrs 属性
> // styles 样式
> // ctx 画布上下文
> new Figure({ attrs, styles }).draw(ctx);
> ```
> 
> 需要绘制线那么使用基础图形：line即可

@LeeZChuan 谢谢，我尝试下

**Comment by wei916159659** [comment]
> > 官方文档提到了这个在画布上绘制基础图形的方法，具体参考使用这个方法即可
> > // 获取基础图形实例
> > // name为基础图形名字，如，'arc', 'circle'等。
> > const Figure = klinecharts.getFigureClass(name);
> > // 实例化并绘制
> > // attrs 属性
> > // styles 样式
> > // ctx 画布上下文
> > new Figure({ attrs, styles }).draw(ctx);
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 需要绘制线那么使用基础图形：line即可
> 
> [@LeeZChuan](https://github.com/LeeZChuan) 谢谢，我尝试下

您好，请问老哥你最终实现了吗，我也有个类似的需要 要在k线图表中标出一条成本线

**Comment by taojunnan** [comment]
@wei916159659 没，后来放弃这个需求了
