### ISSUE TITLE
[Feature] Programmatically modify the yAxis range

### ISSUE THREAD

**Issue by rxdiscovery** [klinecharts/KLineChart#591]
### Feature Description

Hello,

I've been looking for a way to modify the maximum and minimum yAxis values, but without success.

especially since if you modify the Y axis with the mouse, and load new data, the Chart doesn't automatically calculate the new values (max and min) and remains frozen on what you moved with the mouse (is this a bug?).

I don't think this feature exists yet. Can you add it? Or if there's a way to do it, it would be great if someone could tell me how?

Thanks in advance

**Comment by liihuu** [comment]
Double click y-axis

**Comment by rxdiscovery** [comment]
Thank you @liihuu  for this information, it will help me calibrate the range without the manual function.

Just a small remark, the range is not suitable for data with values less than 1 , for example Assets with values 0.xxxx
