### ISSUE TITLE
Date Format for XAxis

### ISSUE THREAD

**Issue by nensimehta** [klinecharts/KLineChart#598]
How to date format same as trading view in klinechart 

Below is sample date when zoom out 
![image](https://github.com/user-attachments/assets/de877e07-d8e4-42e1-a25f-30f0522196f1)

Below is date format when zoom in :- 
![image](https://github.com/user-attachments/assets/a9689ddd-44d6-4d62-8335-0de974e330bb)

I tried to use customApi.formatDate function but that is showing same format when zoom in and out, all the time complete date is being shown. 

How to provide same behavior as tracing view charts for date on XAxis

**Comment by liihuu** [comment]
Supported in v10.

**Comment by nensimehta** [comment]
@liihuu  can you guide me how to enable this in v10 ?
