### ISSUE TITLE
[Feature] Implement a way (in public API) to obtain list of all panes and list of all overlays

### ISSUE THREAD

**Issue by Andrey36652** [klinecharts/KLineChart#605]
### Feature Description

Make it possible to programmatically enumerate all existing panes and overlays on chart.

### To Do

For list of all panes:
Create a new function `getAllPanesIds()` in `Chart` interface that will return list of all ids of all panes like `['candle_pane', 'volume_pane', 'custom_pane_1']` excluding `'x_axis_pane'` (though I'm not sure about it).

For list of all overlays:
Create a new function `getAllOverlaysIds()` in `Chart` interface that should be implemented similarly to panes function.

**Comment by liihuu** [comment]
This commit will be included in the next version, and you can use the api `getOverlays`.
