### ISSUE TITLE
applyMoreData(dataList, more, callback)

### ISSUE THREAD

**Issue by explorster** [klinecharts/KLineChart#606]
what do we use since applyMoreData(dataList, more, callback) has been deprecated since version 9.8.0. ?
Thanks

**Comment by rugia813** [comment]
looks like we should use `setLoadDataCallback` for both new and old data:

```javascript
chart.setLoadDataCallback(async ({ type, data, callback }) => {
        console.log('load data ', type, data);
        if (type === 'backward') {
          callback(await genData(data!.timestamp, 20));
        } else { // forward
          callback(await genData(data!.timestamp, 20), true);
        }
      });
```

**Comment by explorster** [comment]
> looks like we should use `setLoadDataCallback` for both new and old data:
> 
> ```js
> chart.setLoadDataCallback(async ({ type, data, callback }) => {
>         console.log('load data ', type, data);
>         if (type === 'backward') {
>           callback(await genData(data!.timestamp, 20));
>         } else { // forward
>           callback(await genData(data!.timestamp, 20), true);
>         }
>       });
> ```

Thanks rugia813
