### ISSUE TITLE
[Bug] 在webview内使用k线图标，手势抬起之后十字光标不会消失？

### ISSUE THREAD

**Issue by jhmobile** [klinecharts/KLineChart#610]
### 版本

9.8.10

### 复现步骤

在一个手机APP webview内的k线图上，长按显示十字光标，抬起之后十字光标不会消失

### 当前效果

十字光标不会消失，只有进行棍等或者放大操作十字光标才会消失

### 预期效果

手势抬起后，十字光标会消失，或者有手势抬起的回调钩子及光标消失的api，业务端自己在手势抬起后，自己触发光标的消失

### 环境

```markdown
- 系统:
- 浏览器:
- 框架:
```

**Comment by jhmobile** [comment]
手动监听通过设置style已隐藏

**Comment by liihuu** [comment]
移动设备交互设计如此
