### ISSUE TITLE
setDataSpace missing?

### ISSUE THREAD

**Issue by DeeeeLAN** [klinecharts/KLineChart#613]
I noticed setDataSpace is missing from 10.0.0, although I am not sure when it was removed. Is there an updated API that lets me do the same action?

**Comment by liihuu** [comment]
`setBarSpace`

**Comment by DeeeeLAN** [comment]
If I wanted to set exactly a year of data to be visible, what else would I need? 

The size of the chart, using what function?
The number of bars in a year

I divide the size by the number of bars and use setBarSpace to size it appropriately.

Does getSize give me the correct value for this?

**Comment by liihuu** [comment]
Sure, it is best to set the y-axis width to a fixed value.
